### ISSUE TITLE
python3 runserver.py &  (OSError: [WinError 193] %1 is not a valid Win32 application)

### ISSUE THREAD

**Issue by malcolmturnballs** [trinity-project/trinity#20]
Hi all,

Trying to run a node on the TestNet using Windows and came across this error with runserver.py.

Has anyone encountered this issue and know of a way around it?
Some googling suggested it might be related to python 32bit being incompatible with something that's 64bit or visa-versa.

Any help will be appreciated!
-----------------------------
c:\Neo\trinity-master\src\NodeB>python runserver.py &
Traceback (most recent call last):
  File "runserver.py", line 1, in <module>
    from NodeB.app.app import app
  File "C:\Neo\trinity-master\src\NodeB\app\app.py", line 43, in <module>
    from .controller import *
  File "C:\Neo\trinity-master\src\NodeB\app\controller.py", line 4, in <module>
    from NodeB import service
  File "C:\Neo\trinity-master\src\NodeB\service.py", line 4, in <module>
    from NodeB.utils import createMultiSigAddress, ToScriptHash, int_to_hex, con
struct_opdata, privtkey_sign, hex_reverse, \
  File "C:\Neo\trinity-master\src\NodeB\utils.py", line 6, in <module>
    from neocore.KeyPair import KeyPair
  File "C:\Python\Python36-32\lib\site-packages\neocore\KeyPair.py", line 4, in
<module>
    import scrypt
  File "C:\Python\Python36-32\lib\site-packages\scrypt.py", line 11, in <module>

    _scrypt = cdll.LoadLibrary(imp.find_module('_scrypt')[1])
  File "C:\Python\Python36-32\lib\ctypes\__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "C:\Python\Python36-32\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 is not a valid Win32 application

**Comment by pigxo** [comment]
Maybe you can try install the win32.whl , more information https://pypi.python.org/pypi/scrypt/

**Comment by malcolmturnballs** [comment]
Thanks, pigxo.

I installed the .whl file and still received the same error.

**Comment by malcolmturnballs** [comment]
File "C:\Neo\trinity-master\src\NodeB\app\app.py", line 43, in 
from .controller import *

if i exclude this line from app.py, it works, but i suspect it'll stuff something else up down the line.
